// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlpzitFyvahJI65Kn9r4JeevszthjKQdU',
    appId: '1:794438040718:web:be31f73f189b8cb53f1ddf',
    messagingSenderId: '794438040718',
    projectId: 'kahoot-c3b84',
    authDomain: 'kahoot-c3b84.firebaseapp.com',
    storageBucket: 'kahoot-c3b84.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnOMTiTryOy7nXS3qQbyzHgfr-Pkte9XQ',
    appId: '1:794438040718:android:a49b0e4cb8f9dc0b3f1ddf',
    messagingSenderId: '794438040718',
    projectId: 'kahoot-c3b84',
    storageBucket: 'kahoot-c3b84.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDs__EttKBxByOHR_pzc-4x1n6DJVt7RTY',
    appId: '1:794438040718:ios:186256f26f365da33f1ddf',
    messagingSenderId: '794438040718',
    projectId: 'kahoot-c3b84',
    storageBucket: 'kahoot-c3b84.appspot.com',
    iosClientId: '794438040718-882a2n0b8q6ak59cl8ea76l58bk11of3.apps.googleusercontent.com',
    iosBundleId: 'com.example.kahoot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDs__EttKBxByOHR_pzc-4x1n6DJVt7RTY',
    appId: '1:794438040718:ios:8b95e2c32d2a6b643f1ddf',
    messagingSenderId: '794438040718',
    projectId: 'kahoot-c3b84',
    storageBucket: 'kahoot-c3b84.appspot.com',
    iosClientId: '794438040718-g89f92n7j3gga131qflvvb51kl2p9s9u.apps.googleusercontent.com',
    iosBundleId: 'com.example.kahoot.RunnerTests',
  );
}
