import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:kahoot/provider/user_provider.dart';
import 'package:kahoot/screens/authentication/login.dart';
import 'package:provider/provider.dart';

import 'screens/authentication/signup.dart';

void main() {
  // Initialize Firebase
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return ChangeNotifierProvider(
      create: (_)=>UserDataProvider(),
      child: MaterialApp(
        title: 'Map Markers',
        debugShowCheckedModeBanner: false,
        initialRoute: '/login',
        
        routes: {
          '/login': (context) => LogIn(title: 'kahoot'),
          '/signup': (context) => SignUp(),
          // '/friend-list': (context) => FavoritePage(),
          // '/search': (context) => FavoritePage(),
          // '/invites': (context) => FavoritePage(),
          // '/map': (context) => const Info(
          //       title: '',
          //       about: about,
          //     ),
        },
      ),
    );
  }
}


// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 

//TODO connection these firebase options with kahoot
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhXxFoNTJ61143XFE-4VOK1QsGfq8iXNg',
    appId: '1:773643369978:web:879a6c7288b53b47983843',
    messagingSenderId: '773643369978',
    projectId: 'chess-laura-eliise',
    authDomain: 'chess-laura-eliise.firebaseapp.com',
    databaseURL: 'https://chess-laura-eliise-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'chess-laura-eliise.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKCH4LmKNUaq4Ro_2L6Fn07Nxbv8cwSYY',
    appId: '1:773643369978:android:b3c5280a791013b5983843',
    messagingSenderId: '773643369978',
    projectId: 'chess-laura-eliise',
    databaseURL: 'https://chess-laura-eliise-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'chess-laura-eliise.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdtfzEcgfB-casxoQnrhLG0ODvikD5qZs',
    appId: '1:773643369978:ios:f3d5257584d132ee983843',
    messagingSenderId: '773643369978',
    projectId: 'chess-laura-eliise',
    databaseURL: 'https://chess-laura-eliise-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'chess-laura-eliise.appspot.com',
    iosClientId: '773643369978-mimiprcuipvrqagfagef8bgftl4lg4cf.apps.googleusercontent.com',
    iosBundleId: 'com.example.chess',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdtfzEcgfB-casxoQnrhLG0ODvikD5qZs',
    appId: '1:773643369978:ios:f3d5257584d132ee983843',
    messagingSenderId: '773643369978',
    projectId: 'chess-laura-eliise',
    databaseURL: 'https://chess-laura-eliise-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'chess-laura-eliise.appspot.com',
    iosClientId: '773643369978-mimiprcuipvrqagfagef8bgftl4lg4cf.apps.googleusercontent.com',
    iosBundleId: 'com.example.chess',
  );
}
